"""
SA - Master Dashboard | Patcher: gitignore scripts/*.bak* + report tracked .bak files

Problem (S38 handoff carry):
    Patcher discipline emits pre-write sidecar backups (build_dashboard.py.bak-
    pre-<op>-<ts>) of order ~700KB each. The repo currently has 95 such files
    under scripts/ totalling ~30MB, most of which are tracked in git --
    bloating every commit and the repo history.

Scope (per S38 handoff -- explicit boundary):
    scripts/*.bak  AND  scripts/*.bak-*
    NOT included: data/*.bak* (8 tracked, stable historical taxonomy/snapshot
    backups -- flagged separately for Richard's decision); ic-ratings-dashboard
    .bak-pre-sync-*.html at the repo root (1 file).

What this script does:
    1. Adds a MARKER-guarded section to .gitignore covering scripts/*.bak and
       scripts/*.bak-* . Idempotent on MARKER.
    2. Reports the currently-tracked .bak files under scripts/ that the new
       rules will cover.
    3. Prints the exact one-liner Richard runs to untrack them.

Doctrine compliance:
    - Reads source via `git show HEAD:` (FUSE-immune).
    - Idempotent on MARKER.
    - Working-tree-vs-HEAD safety gate (relaxed in --test).
    - Pre-write backup as sidecar (.bak-pre-gitignore-scripts-{TS}).
    - --test dry-run mode.

Run order on Windows-side:
    python scripts\\patch_md_gitignore_scripts_bak_s39_2026_05_16.py --test
    python scripts\\patch_md_gitignore_scripts_bak_s39_2026_05_16.py
    # The script will print a "git rm --cached" one-liner; copy-paste and run it:
    git ls-files 'scripts/*.bak*' | %{ git rm --cached -- $_ }     # PowerShell
    # OR (Git Bash):
    git ls-files 'scripts/*.bak*' | xargs git rm --cached
    # Then:
    git add .gitignore
    git status   # sanity check: only .gitignore + deletions of scripts/*.bak* should show
    git commit -m "chore: gitignore + untrack scripts/*.bak* (S39 repo hygiene, ~30MB of patcher backups)"
    git push
"""
from __future__ import annotations
import datetime as _dt
import hashlib
import os
import subprocess
import sys
import tempfile

REPO_ROOT_HINT = "master-dashboard"
TARGET_REL = ".gitignore"
MARKER = "# MD-V2-S39-GITIGNORE-SCRIPTS-BAK"

# Block to append. Two patterns to catch both naming forms in use today.
APPEND_BLOCK = """
# MD-V2-S39-GITIGNORE-SCRIPTS-BAK (16-May-26)
# Patcher pre-write backups (~700KB each, ~30MB accumulated). Pure local-recovery
# artefacts -- not needed in repo history. Generated by patcher scripts that
# follow the doctrinal sidecar pattern .bak-pre-<op>-<YYYYMMDD-HHMMSS>.
scripts/*.bak
scripts/*.bak-*
"""

def _find_repo_root() -> str:
    cur = os.path.abspath(os.path.dirname(__file__))
    cand = os.path.abspath(os.path.join(cur, os.pardir))
    if os.path.basename(cand) == REPO_ROOT_HINT and os.path.exists(os.path.join(cand, ".git")):
        return cand
    walk = cur
    for _ in range(6):
        if os.path.exists(os.path.join(walk, ".git")):
            return walk
        walk = os.path.abspath(os.path.join(walk, os.pardir))
    raise SystemExit(f"[ABORT] cannot locate repo root from {cur}")

def _git_show_head(repo: str, rel: str) -> bytes:
    out = subprocess.run(
        ["git", "show", f"HEAD:{rel}"],
        cwd=repo, check=True, capture_output=True,
    )
    return out.stdout

def _git_tracked_scripts_bak(repo: str) -> list[str]:
    """Return list of git-tracked paths under scripts/ matching *.bak or *.bak-*."""
    out = subprocess.run(
        ["git", "ls-files"],
        cwd=repo, check=True, capture_output=True, text=True,
    )
    matched = []
    for line in out.stdout.splitlines():
        if not line.startswith("scripts/"):
            continue
        base = os.path.basename(line)
        if base.endswith(".bak") or ".bak-" in base:
            matched.append(line)
    return sorted(matched)

def _wt_bytes(repo: str, rel: str) -> bytes:
    p = os.path.join(repo, rel)
    if not os.path.exists(p):
        return b""
    with open(p, "rb") as fh:
        return fh.read()

def _sha256(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()

def main(argv: list[str]) -> int:
    test_mode = "--test" in argv
    repo = _find_repo_root()
    rel = TARGET_REL
    abs_target = os.path.join(repo, rel)

    print(f"[*] Repo root:   {repo}")
    print(f"[*] Target:      {rel}")
    print(f"[*] Mode:        {'DRY-RUN (--test)' if test_mode else 'WRITE'}")

    # --- 1. Read HEAD source ---
    head_src = _git_show_head(repo, rel)
    print(f"[*] HEAD bytes:  {len(head_src)}")
    print(f"[*] HEAD sha256: {_sha256(head_src)}")

    # --- 2. Working-tree safety gate ---
    wt_src = _wt_bytes(repo, rel)
    print(f"[*] WT bytes:    {len(wt_src)}")
    print(f"[*] WT sha256:   {_sha256(wt_src)}")
    if wt_src != head_src:
        if test_mode:
            print("[WARN] Working tree diverges from HEAD (likely FUSE stale-cache).")
            print("       Dry-run continues -- gates operate on HEAD source.")
            print("       The WRITE path will still refuse if WT != HEAD.")
        else:
            print("[ABORT] Working tree diverges from HEAD. Refusing to patch.")
            print("        Run `git status` and resolve before re-running.")
            return 2

    src = head_src.decode("utf-8")

    # --- 3. Idempotency check ---
    if MARKER in src:
        print(f"[OK] MARKER already present ({MARKER!r}) - patch is idempotent.")
        # Still report tracked .bak files in case the untrack step was skipped.
        tracked = _git_tracked_scripts_bak(repo)
        print(f"\n[*] Currently tracked scripts/*.bak* files: {len(tracked)}")
        if tracked:
            print("    (.gitignore is in place; these still need to be untracked.)")
            for p in tracked[:5]:
                print(f"      {p}")
            if len(tracked) > 5:
                print(f"      ... and {len(tracked) - 5} more")
        return 0

    # --- 4. Build new source ---
    new_src = src.rstrip("\n") + "\n" + APPEND_BLOCK
    delta = len(new_src.encode("utf-8")) - len(src.encode("utf-8"))
    print(f"[*] Byte delta:  +{delta}")
    print(f"[*] New sha256:  {_sha256(new_src.encode('utf-8'))}")

    # --- 5. Report tracked files that would now match ---
    tracked = _git_tracked_scripts_bak(repo)
    total_bytes = 0
    for p in tracked:
        try:
            total_bytes += os.path.getsize(os.path.join(repo, p))
        except OSError:
            pass
    print(f"\n[*] Currently tracked scripts/*.bak* files: {len(tracked)} ({total_bytes:,} bytes on disk)")

    # --- 6. Show diff ---
    print("\n--- DIFF (unified) ---")
    import difflib
    diff = difflib.unified_diff(
        src.splitlines(keepends=True),
        new_src.splitlines(keepends=True),
        fromfile=f"HEAD:{rel}",
        tofile=f"PATCHED:{rel}",
        n=2,
    )
    sys.stdout.writelines(diff)
    print("--- END DIFF ---\n")

    if test_mode:
        print("[OK] DRY-RUN: gates passed. Re-run without --test to write.")
        if tracked:
            print(f"\n    After write, run this to untrack the {len(tracked)} existing .bak* files:")
            print(f"      # Git Bash / Linux:")
            print(f"      git ls-files 'scripts/*.bak*' | xargs git rm --cached")
            print(f"      # PowerShell:")
            print(f"      git ls-files 'scripts/*.bak*' | %{{ git rm --cached -- $_ }}")
        return 0

    # --- 7. Pre-write backup ---
    ts = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    bak = abs_target + f".bak-pre-gitignore-scripts-{ts}"
    with open(bak, "wb") as fh:
        fh.write(wt_src)
    print(f"[*] Backup:      {os.path.relpath(bak, repo)}")

    # --- 8. Write via temp + os.replace ---
    target_dir = os.path.dirname(abs_target) or repo
    fd, tmp_out = tempfile.mkstemp(prefix=".gi-patch-", dir=target_dir, text=False)
    os.close(fd)
    with open(tmp_out, "wb") as fh:
        fh.write(new_src.encode("utf-8"))
    os.replace(tmp_out, abs_target)

    # --- 9. Post-write byte-verify ---
    after = _wt_bytes(repo, rel)
    if _sha256(after) != _sha256(new_src.encode("utf-8")):
        print("[ABORT] Post-write sha256 mismatch! Restore from .bak-pre-* sidecar.")
        return 6
    if MARKER not in after.decode("utf-8"):
        print("[ABORT] Post-write MARKER missing.")
        return 7
    print(f"[OK] WRITE complete. {len(after)} bytes on disk. MARKER present.")

    # --- 10. Print follow-up commands ---
    if tracked:
        print(f"\n[*] Next step -- untrack the {len(tracked)} existing .bak* files ({total_bytes:,} bytes):")
        print(f"    # Git Bash / Linux:")
        print(f"    git ls-files 'scripts/*.bak*' | xargs git rm --cached")
        print(f"    # PowerShell:")
        print(f"    git ls-files 'scripts/*.bak*' | %{{ git rm --cached -- $_ }}")
        print(f"\n[*] Then:")
        print(f"    git status   # sanity check")
        print(f"    git add .gitignore")
        print(f"    git commit -m \"chore: gitignore + untrack scripts/*.bak* (S39 repo hygiene)\"")
        print(f"    git push")
    else:
        print(f"\n[*] No tracked .bak* files under scripts/ to untrack.")
        print(f"    git add .gitignore && git commit && git push")
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
