"""
rename_chart_files.py — Rename chart files to match new canonical tickers.

After apply_taxonomy_patch.py renamed 24 watchlist tickers and dropped 2,
the chart files in master-dashboard/charts/ still use the old ticker filenames
(e.g. EKTA-SE.js, but the watchlist now says EKTA.B-SE).

This script:
  - Renames each old_ticker.js -> new_ticker.js
  - Reports any missing source files (chart not yet generated)
  - Optionally deletes chart files for the 2 dropped tickers (UNA-NL, RDSA-NL)
  - Idempotent: skips renames where the destination already exists

Usage:  python rename_chart_files.py --dry-run    # show plan
        python rename_chart_files.py              # apply
        python rename_chart_files.py --delete-dropped   # also delete UNA-NL.js + RDSA-NL.js
"""
import argparse
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
CHARTS_DIR = SCRIPT_DIR.parent / "charts"

# Mirror of WL_RENAMES from apply_taxonomy_patch.py
RENAMES = {
    "ASSA-SE":  "ASSA.B-SE",
    "BEIJ-SE":  "BEIJ.B-SE",
    "CLAS-SE":  "CLAS.B-SE",
    "EKTA-SE":  "EKTA.B-SE",
    "ELUX-SE":  "ELUX.B-SE",
    "GETI-SE":  "GETI.B-SE",
    "HEXA-SE":  "HEXA.B-SE",
    "LIFCO-SE": "LIFCO.B-SE",
    "NIBE-SE":  "NIBE.B-SE",
    "NOLA-SE":  "NOLA.B-SE",
    "NOVO-DK":  "NOVO.B-DK",
    "NSIS-DK":  "NSIS.B-DK",
    "PEAB-SE":  "PEAB.B-SE",
    "SAGA-SE":  "SAGA.B-SE",
    "SKA-SE":   "SKA.B-SE",
    "SKF-SE":   "SKF.B-SE",
    "TEL2-SE":  "TEL2.B-SE",
    "VOLV-SE":  "VOLV.B-SE",
    "ATCO-SE":  "ATCO.A-SE",
    "BT-GB":    "BT.A-GB",
    "AIR-DE":   "AIR-FR",
    "CARLB-DK": "CARL.B-DK",
    "NKT-SE":   "NKT-DK",
    "PRY-GB":   "PRY-IT",
}

DROPPED = ["UNA-NL", "RDSA-NL"]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--delete-dropped", action="store_true",
                        help="Also delete UNA-NL.js and RDSA-NL.js")
    args = parser.parse_args()

    if not CHARTS_DIR.exists():
        print(f"ERROR: charts dir not found at {CHARTS_DIR}")
        return

    print(f"Charts directory: {CHARTS_DIR}")
    print(f"Total .js files: {len(list(CHARTS_DIR.glob('*.js')))}")
    print()

    renamed = 0
    skipped_already_done = 0
    missing_source = 0
    blocked_dest_exists = 0

    for old, new in RENAMES.items():
        old_path = CHARTS_DIR / f"{old}.js"
        new_path = CHARTS_DIR / f"{new}.js"

        if not old_path.exists():
            if new_path.exists():
                # Already renamed, idempotent skip
                skipped_already_done += 1
                continue
            else:
                print(f"  MISSING:    {old}.js (no source, will be regenerated by pipeline)")
                missing_source += 1
                continue

        if new_path.exists():
            print(f"  BLOCKED:    {old}.js -> {new}.js (destination already exists, manual review)")
            blocked_dest_exists += 1
            continue

        print(f"  Rename:     {old}.js -> {new}.js")
        if not args.dry_run:
            os.rename(old_path, new_path)
        renamed += 1

    print()
    print(f"Summary: renamed={renamed}, already-done={skipped_already_done}, "
          f"missing-source={missing_source}, blocked={blocked_dest_exists}")

    if args.delete_dropped:
        print()
        print("── Deleting chart files for dropped tickers ──")
        for tk in DROPPED:
            p = CHARTS_DIR / f"{tk}.js"
            if p.exists():
                print(f"  Delete: {tk}.js")
                if not args.dry_run:
                    p.unlink()
            else:
                print(f"  Already absent: {tk}.js")

    if args.dry_run:
        print("\nDRY-RUN complete. Re-run without --dry-run to apply.")


if __name__ == "__main__":
    main()
